### ISSUE TITLE
New Connection Issue Just Started

### ISSUE THREAD

**Issue by mbellas-tkxs** [Inumedia/SlackAPI#177] opened 2019-04-30 13:29 UTC
Hey,
I've been using this library for over a year without any issues, it's been great. Yesterday (4/29/19) I started being unable to connect.  I switched over to the 1.0.7 source code from the nuget package and this is the error I'm getting on connecting:

Newtonsoft.Json.JsonSerializationException: Error converting value "not_set" to type 'SlackAPI.SearchSort'. Path 'self.prefs.search_sort', line 1, position 332. ---> System.ArgumentException: Requested value 'not_set' was not found.

**Comment by mbellas-tkxs** [comment] 2019-04-30 13:51
Was able to get around it and connect again by adding "not-set" to SearchSort:

    public enum SearchSort
    {
        not_set,
        score,
        timestamp
    }

**Comment by PeterJFerrarotto** [comment] 2019-04-30 14:31
@mbellas-tkxs there's also a new "relevant" value, usually set for the search_file_sort and search_channel_sort, but it's possible it could be set for the included search_sort in the current model.

**Comment by gapin** [comment] 2019-05-01 23:07
same here! do you think it's going to be a fix for this issue, soon ?

**Comment by dicko2** [comment] 2019-05-03 04:30
Confirmed this is an issue, i have replicated and fixed by adding value in enum

**Comment by Kvariani** [comment] 2019-05-03 12:24
hi. 
can you add new dll in nuget? 
thank you very much!

**Comment by Inumedia** [comment] 2019-05-03 13:47
This should be fixed with the merge of #180 and the release of the 1.0.8 NuGet package. Can someone verify that this has been fixed for them so I can close out this issue?

https://www.nuget.org/packages/SlackAPI/1.0.8

**Comment by wiktor-golonka** [comment] 2019-05-03 13:54
@Inumedia : Thanks. New version is working ok.

**Comment by Kvariani** [comment] 2019-05-03 14:00
i can confirm, that the problem was solved

**Closed** 2019-05-03 14:19 UTC

**Comment by martinmine** [comment] 2019-05-08 21:22
I have a similar problem but with `not_set_new_user`, I added PR #183 to resolve this issue.

**Comment by wiktor-golonka** [comment] 2019-05-13 09:28
@Inumedia: 
Could you please review PR #183 ? 

Thanks
