### ISSUE TITLE
Nuget package does not have "netstandard/.net core" support as stated in README.md

### ISSUE THREAD

**Issue by vonzepp** [Inumedia/SlackAPI#128] opened 2017-11-20 08:29 UTC
https://www.nuget.org/packages/SlackAPI/
have only single framework target: .Net Framework 4.5
As I understand project already have "netstandard" build. Could you please update nuget package.

**Comment by razfriman** [comment] 2018-05-19 03:16
This would help me tremendously

**Comment by razfriman** [comment] 2018-06-10 00:47
Any updates on this?

**Comment by josephcooney** [comment] 2018-09-20 14:03
There is a 1.0.6 build on the myget feed here https://www.myget.org/F/slackapi/api/v3/index.json that supports netstandard.

**Comment by gpailler** [comment] 2018-11-01 17:54
Official 1.0.6 will be published soon on Nuget

**Comment by gpailler** [comment] 2018-11-01 17:57
Duplicate of #123

**Comment by gpailler** [comment] 2018-11-07 08:01
1.0.7 released

**Closed by gpailler** 2018-11-07 08:01 UTC
