### ISSUE TITLE
Please add "attachments[]" field to class Message

### ISSUE THREAD

**Issue by videokojot** [Inumedia/SlackAPI#101] opened 2017-04-01 13:26 UTC
Class Message is missing attachments[] field.
For example when calling method [https://api.slack.com/methods/im.history](url) using WebClient like this and there is message with attachments:
```

            WebClient wc = new WebClient();
            wc.QueryString.Add("channel", "CHANNEL");
            wc.QueryString.Add("token", "YOUR_TOKEN");
            string result = wc.DownloadString("https://slack.com/api/im.history");
            var result = System.Text.RegularExpressions.Regex.Unescape(result);
```
you will recieve json with attachments[] field property.

But when using SlackClient there is no prop. like this on Message class...

Please add it,

Thank you very much.

**Comment by juliepromact** [comment] 2017-04-19 06:41
@cincibuch did you work on this issue ?

**Comment by cincibuch** [comment] 2017-04-20 08:36
i did not. i just did not used SlackAPI for this case.

**Comment by juliepromact** [comment] 2017-04-21 09:25
ok

**Comment by gpailler** [comment] 2018-11-02 02:17
Duplicate of #136 
Fixed in the scope of #142

**Closed** 2018-11-02 02:17 UTC
