### ISSUE TITLE
Message timestamp (ts) precision

### ISSUE THREAD

**Issue by stpeteparadox** [Inumedia/SlackAPI#74] opened 2016-11-18 02:42 UTC
Hi, I think this issue is somewhat related to a prior mis-diagnosed issue I posted about ( #45 ). Apologies in advance if I'm misunderstanding anything, or if there's a simple solution I'm not seeing.

My suggestion here is that Message class (Message.cs) include a string property that preserves the timestamp (ts) property originally sent down in json from Slack. I think that somewhere in the process of converting the ts property to c# DateTime, or later if converting from that DateTime back to Slack ts format (say, for deleting a message), precision is lost (and Slack says it cannot delete the message as it cannot find it). If we preserve the original string format ts property, in addition to having a DateTime prop, at least we can always rely on the string property as being the precise truth (in cases where that timestamp information needs to be sent back up to Slack).

Let me describe a concrete example of where this problem is manifesting for me. 

I have a custom Bot that handles a number of administrative duties, on a scheduled basis, including deleting historic messages according to various rules. To go about doing so, the bot calls GetChannelHistoryAsync or GetGroupHistoryAsync (which themselves call GetHistoryAsync), to return lists of messages in specified channels/group.

It then loops through the returned list of messages and calls DeleteMessageAsync(string channelId, DateTime ts) method where appropriate.. The DateTime ts value that is fed to DeleteMessageAsync comes directly from the ts property on messages in the message list returned from GetChannelHistoryAsync. 

 The problem arises because Slack in many cases responds to that chat.delete command with the message_not_found error. This occurs in 30-40% of delete commands sent to Slack.

I've worked through the Fiddler logs, comparing the message timestamp values returned by Slack (when called with GetChannelHistoryAsync) against the message timestamp value sent to Slack with the chat.delete command. What I've noticed is that where Slack responds with the message_not_found error, it is because the original Slack message string timestamp had 6 decimal places (#.000000), whereas the timestamp sent via chat.delete only has 5 decimal places.

I've tried seeing what I can do to override behavior to force the ToProperTimeStamp extension to include the sixth decimal digit, but while that resolves the chat.delete problem, it results in a new error during JSON parsing of the results returned by GetChannelHistoryAsync. I'm not sure if I'm misdiagnosing the issue here.

As an easier potential solution, I suggest the additional string-based timestamp property for the Message class, and refer to the following message thread on the official Slack issue board: [https://github.com/slackhq/slack-api-docs/issues/7](https://github.com/slackhq/slack-api-docs/issues/7)   ...specifically the first response from Slack member paulhammond: ". . . message timestamps, which always use the "ts" name (eg: "ts", "event_ts"). These are returned as strings. Even though they look like floats, they should always be stored and compared as strings - because floats occasionally lose precision and that would be bad here."

Anyone else run into this issue?

Anyhow thanks again for this awesome library!

**Comment by Inumedia** [comment] 2016-11-18 04:17
Hmmmm, so I ran into that issue originally and had hoped that ToProperTimeStamp would fix the underlying issue but that doesn't seem to be happening. Maybe they switched their internal version to a double or something, either way that's not really a maintainable way to implement this.

Unfortunately I'm not fond of the idea of switching a float to a string because if anyone is using it for something else, there'll be regressions.

Could you try seeing if the decimal type (in place of float) would help with your issue?

**Comment by stpeteparadox** [comment] 2016-11-18 05:27
Thanks. I was only suggesting a new property of type string to preserve the original timestamp, in addition to the existing DateTime ts prop. I guess not best practice; kinda dirty.

Already was using decimal type in the ToProperTimeStamp adjustments, otherwise not making any other changes elsewhere. Data retrieved from GetHistory isn't stored to db or anything, just immediately reused to send delete commands, without any type conversion except that which takes place already in the SlackAPI JSON deserialization on the way in, and then in ToProperTimeStamp on the way back out.

Will keep fiddling. Thanks!

**Comment by stpeteparadox** [comment] 2016-11-18 07:30
Hi, looks like my issue is now resolved.

What I did was to override the ToProperTimeStamp extension and change the line
string result = ((that.ToUniversalTime().Ticks - 621355968000000000m) / 10000000m).ToString("G17");

to:

string result = ((that.ToUniversalTime().Ticks - 621355968000000000m) / 10000000m).ToString("0.000000");

Everything is now working smoothly (at least in all the ways I use this library). My prior mention of a new error when changing the above is also resolved with the ToString format as above.

I am not very familiar with the standard numeric format strings, but in my case G17 was not working,  resulting in only 5 decimal places, when Slack was expecting 6 (at least now). Not sure if 0.000000 is the most appropriate solution here.

thanks

**Comment by Inumedia** [comment] 2016-11-18 14:21
Neat. Would you mind making a quick pull request for that?

**Comment by gpailler** [comment] 2017-03-15 03:45
Fixed with Nuget package 1.0.5.93

**Closed by gpailler** 2017-03-15 03:45 UTC
Labels: bug, needs response

**Comment by PeteFox** [comment] 2020-04-03 18:47
I was about to post a separate issue about this, but luckily Github suggested this thread.

However, I agree with @stpeteparadox that it feels kinda strange to rewrite something that's meant to be a unique ID. 

IMHO, the more correct way would be to preserve TS as a string and just have an extension method to extract the DateTime whenever that's needed for whatever reason one might have. (Or maybe just another property on the model, that has `get` returning TS as a DateTime).

Why try to change the API specification set by the developers you are building a library around?

**From Stripe's documentation:**
> There are a few additional fields that describe the author (such as user or bot_id), but there's also an additional `ts`? field. The `ts` value is essentially the ID of the message, guaranteed unique within the context of a channel or conversation.
> 
> They _look like_ UNIX/epoch timestamps, hence `ts`, with specified milliseconds. They'll even sort like the same. But they're message IDs, even if they're partially composed in seconds-since-the-epoch.
> 
> The ts of a message can be used in many operations such as replying to it in a thread, or modifying the message. But it can also be used to retrieve the message by itself.


Other than that - thank you for the great work. I might submit a pull request for a few things soon.
